robot-name: Improved code based on HLint's suggestions.
- Remove variable named `pattern` in `src/Example` to workaround
HLint's bug that causes a parse error.

```
./src/Example.hs:19:31: Error: Parse error: pattern
Found:
    generateName :: IO String
  > generateName = mapM randomRIO pattern
      where pattern = [ letter, letter, digit, digit, digit ]
            letter = ('A', 'Z')
```

- Simplify code with `fmap`, as suggested.

```
./src/Example.hs:10:11: Suggestion: Use fmap
Found:
  generateName >>= newMVar >>= return . Robot
Why not:
  fmap Robot (generateName >>= newMVar)
```

- Create a function `testPersistence` to reduce code duplication.

```
./test/Tests.hs:34:13: Warning: Reduce duplication
Found:
  n1 <- robotName r
  n2 <- robotName r
  n3 <- robotName r
  n1 `shouldBe` n2
  n1 `shouldBe` n3
Why not:
  Combine with ./test/Tests.hs:53:13
```